name: Bug report
description: Create a report to help us improve
labels:
  - needs triage
body:
  - type: markdown
    attributes:
      value: >
        DuckDB has several repositories for different components, please make sure you're raising your issue in the correct one:

          * [Documentation/website](https://github.com/duckdb/duckdb-web/issues/new)
          * APIs:
            * [duckdb-node](https://github.com/duckdb/duckdb-node/issues/new)
            * [duckdb-r](https://github.com/duckdb/duckdb-r/issues/new)
            * [duckdb-rs](https://github.com/duckdb/duckdb-rs/issues/new)
            * [duckdb-wasm](https://github.com/duckdb/duckdb-wasm/issues/new)
            * [go-duckdb](https://github.com/marcboeker/go-duckdb/issues/new)
          * Extensions:
            * [AWS extension](https://github.com/duckdb/duckdb_aws/issues/new)
            * [Azure extension](https://github.com/duckdb/duckdb_azure/issues/new)
            * [Iceberg extension](https://github.com/duckdb/duckdb_iceberg/issues/new)
            * [MySQL extension](https://github.com/duckdb/duckdb_mysql/issues/new)
            * [Postgres scanner](https://github.com/duckdb/postgres_scanner/issues/new)
            * [Spatial extension](https://github.com/duckdb/duckdb_spatial/issues/new)
            * [SQLite scanner](https://github.com/duckdb/sqlite_scanner/issues/new)

        If none of the above repositories are applicable, feel free to raise it in this one

        Please report security vulnerabilities using GitHub's [report vulnerability form](https://github.com/duckdb/duckdb/security/advisories/new).

  - type: textarea
    attributes:
      label: What happens?
      description: A short, clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior. Please paste the code and the output as text, and avoid using screenshots. Please use [code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) for formatting and add the required imports for Python scripts (e.g., import duckdb). Bonus points if the steps only include SQL queries.
    validations:
      required: true

  - type: markdown
    attributes:
      value: "# Environment (please complete the following information):"
  - type: input
    attributes:
      label: "OS:"
      placeholder: e.g., iOS
      description: Please include operating system version and architecture (e.g., aarch64, x86, x64, etc)
    validations:
      required: true
  - type: input
    attributes:
      label: "DuckDB Version:"
      placeholder: e.g., 22
    validations:
      required: true
  - type: input
    attributes:
      label: "DuckDB Client:"
      placeholder: e.g., Python
    validations:
      required: true

  - type: markdown
    attributes:
      value: "# Identity Disclosure:"
  - type: input
    attributes:
      label: "Full Name:"
      placeholder: e.g., John Doe
    validations:
      required: true
  - type: input
    attributes:
      label: "Affiliation:"
      placeholder: e.g., Oracle
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        If the above is not given and is not obvious from your GitHub profile page, we might close your issue without further review. Please refer to the [reasoning behind this rule](https://berthub.eu/articles/posts/anonymous-help/) if you have questions.

        # Before Submitting

  - type: dropdown
    attributes:
      label: Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?
      description: |
        * **Python**: `pip install duckdb --upgrade --pre`
        * **R**: `install.packages('duckdb', repos=c('https://duckdb.r-universe.dev', 'https://cloud.r-project.org'))`
        * **Other Platforms**: You can find links to binaries [here](https://duckdb.org/docs/installation/) or compile from source.
      options:
        - I have tested with a nightly build
        - I have tested with a release build (and could not test with a nightly build)
        - I have not tested with any build
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
      options:
        - label: Yes, I have
          required: true
